In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
df

artist                   song  \
0              ABBA  Ahe's My Kind Of Girl   
1              ABBA       Andante, Andante   
2              ABBA         As Good As New   
3              ABBA                   Bang   
4              ABBA       Bang-A-Boomerang   
...             ...                    ...   
57645  Ziggy Marley          Good Old Days   
57646  Ziggy Marley          Hand To Mouth   
57647          Zwan           Come With Me   
57648          Zwan                 Desire   
57649          Zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  
0      Look at her face, it's a wonderful face  \r\nA...  
1      Take it easy with me, please  \r\nTouch me gen...  
2      I'll never know why I had to go  \r\nWhy I had...  
3      Making somebody happy is a question of give an...  
4      Making somebody happy is a question of give an...  
...                                                  ...  
57645  Irie days come on play  \r\nLet the angels fly...  
57646  Power to the workers  \r\nMore power  \r\nPowe...  
57647  all you need  \r\nis something i'll believe  \...  
57648  northern star  \r\nam i frightened  \r\nwhere ...  
57649  come in  \r\nmake yourself at home  \r\ni'm a ...  

[57650 rows x 4 columns]

## Content Based Recomandation System

In [4]:
%pip install rake_nltk

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\abhay\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np
from rake_nltk import Rake
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
df

artist                   song  \
0              ABBA  Ahe's My Kind Of Girl   
1              ABBA       Andante, Andante   
2              ABBA         As Good As New   
3              ABBA                   Bang   
4              ABBA       Bang-A-Boomerang   
...             ...                    ...   
57645  Ziggy Marley          Good Old Days   
57646  Ziggy Marley          Hand To Mouth   
57647          Zwan           Come With Me   
57648          Zwan                 Desire   
57649          Zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  
0      Look at her face, it's a wonderful face  \r\nA...  
1      Take it easy with me, please  \r\nTouch me gen...  
2      I'll never know why I had to go  \r\nWhy I had...  
3      Making somebody happy is a question of give an...  
4      Making somebody happy is a question of give an...  
...                                                  ...  
57645  Irie days come on play  \r\nLet the angels fly...  
57646  Power to the workers  \r\nMore power  \r\nPowe...  
57647  all you need  \r\nis something i'll believe  \...  
57648  northern star  \r\nam i frightened  \r\nwhere ...  
57649  come in  \r\nmake yourself at home  \r\ni'm a ...  

[57650 rows x 4 columns]

In [7]:
import string
for i in range(len(df['text'])):
    df['text'][i] = df['text'][i].translate(str.maketrans('', '', string.punctuation))

df


artist                   song  \
0              ABBA  Ahe's My Kind Of Girl   
1              ABBA       Andante, Andante   
2              ABBA         As Good As New   
3              ABBA                   Bang   
4              ABBA       Bang-A-Boomerang   
...             ...                    ...   
57645  Ziggy Marley          Good Old Days   
57646  Ziggy Marley          Hand To Mouth   
57647          Zwan           Come With Me   
57648          Zwan                 Desire   
57649          Zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  
0      Look at her face its a wonderful face  \r\nAnd...  
1      Take it easy with me please  \r\nTouch me gent...  
2      Ill never know why I had to go  \r\nWhy I had ...  
3      Making somebody happy is a question of give an...  
4      Making somebody happy is a question of give an...  
...                                                  ...  
57645  Irie days come on play  \r\nLet the angels fly...  
57646  Power to the workers  \r\nMore power  \r\nPowe...  
57647  all you need  \r\nis something ill believe  \r...  
57648  northern star  \r\nam i frightened  \r\nwhere ...  
57649  come in  \r\nmake yourself at home  \r\nim a b...  

[57650 rows x 4 columns]

In [8]:
df['Key_words'] = ''   # initializing a new column
r = Rake()   # using Rake to remove stop words

In [9]:
df

artist                   song  \
0              ABBA  Ahe's My Kind Of Girl   
1              ABBA       Andante, Andante   
2              ABBA         As Good As New   
3              ABBA                   Bang   
4              ABBA       Bang-A-Boomerang   
...             ...                    ...   
57645  Ziggy Marley          Good Old Days   
57646  Ziggy Marley          Hand To Mouth   
57647          Zwan           Come With Me   
57648          Zwan                 Desire   
57649          Zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text Key_words  
0      Look at her face its a wonderful face  \r\nAnd...            
1      Take it easy with me please  \r\nTouch me gent...            
2      Ill never know why I had to go  \r\nWhy I had ...            
3      Making somebody happy is a question of give an...            
4      Making somebody happy is a question of give an...            
...                                                  ...       ...  
57645  Irie days come on play  \r\nLet the angels fly...            
57646  Power to the workers  \r\nMore power  \r\nPowe...            
57647  all you need  \r\nis something ill believe  \r...            
57648  northern star  \r\nam i frightened  \r\nwhere ...            
57649  come in  \r\nmake yourself at home  \r\nim a b...            

[57650 rows x 5 columns]

In [10]:
for index, row in df.iterrows():
    r.extract_keywords_from_text(row['text'])   # to extract key words 
    key_words_dict_scores = r.get_word_degrees()    # to get dictionary with key words and their similarity scores
    row['Key_words'] = list(key_words_dict_scores.keys())

In [11]:
df

artist                   song  \
0              ABBA  Ahe's My Kind Of Girl   
1              ABBA       Andante, Andante   
2              ABBA         As Good As New   
3              ABBA                   Bang   
4              ABBA       Bang-A-Boomerang   
...             ...                    ...   
57645  Ziggy Marley          Good Old Days   
57646  Ziggy Marley          Hand To Mouth   
57647          Zwan           Come With Me   
57648          Zwan                 Desire   
57649          Zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  \
0      Look at her face its a wonderful face  \r\nAnd...   
1      Take it easy with me please  \r\nTouch me gent...   
2      Ill never know why I had to go  \r\nWhy I had ...   
3      Making somebody happy is a question of give an...   
4      Making somebody happy is a question of give an...   
...                                                  ...   
57645  Irie days come on play  \r\nLet the angels fly...   
57646  Power to the workers  \r\nMore power  \r\nPowe...   
57647  all you need  \r\nis something ill believe  \r...   
57648  northern star  \r\nam i frightened  \r\nwhere ...   
57649  come in  \r\nmake yourself at home  \r\nim a b...   

                                               Key_words  
0      [look, face, wonderful, means, something, spec...  
1      [take, easy, please, touch, gently, like, summ...  
2      [ill, never, know, go, put, lousy, rotten, sho...  
3      [making, somebody, happy, question, give, take...  
4      [making, somebody, happy, question, give, take...  
...                                                  ...  
57645  [irie, days, come, play, let, angels, fly, dev...  
57646  [power, workers, need, got, free, zone, workin...  
57647  [need, something, ill, believe, flashlights, h...  
57648  [northern, star, frightened, go, rest, cant, s...  
57649  [come, make, home, im, bit, late, hate, wait, ...  

[57650 rows x 5 columns]

In [12]:
df['artist'] = df['artist'].str.lower()
df

artist                   song  \
0              abba  Ahe's My Kind Of Girl   
1              abba       Andante, Andante   
2              abba         As Good As New   
3              abba                   Bang   
4              abba       Bang-A-Boomerang   
...             ...                    ...   
57645  ziggy marley          Good Old Days   
57646  ziggy marley          Hand To Mouth   
57647          zwan           Come With Me   
57648          zwan                 Desire   
57649          zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  \
0      Look at her face its a wonderful face  \r\nAnd...   
1      Take it easy with me please  \r\nTouch me gent...   
2      Ill never know why I had to go  \r\nWhy I had ...   
3      Making somebody happy is a question of give an...   
4      Making somebody happy is a question of give an...   
...                                                  ...   
57645  Irie days come on play  \r\nLet the angels fly...   
57646  Power to the workers  \r\nMore power  \r\nPowe...   
57647  all you need  \r\nis something ill believe  \r...   
57648  northern star  \r\nam i frightened  \r\nwhere ...   
57649  come in  \r\nmake yourself at home  \r\nim a b...   

                                               Key_words  
0      [look, face, wonderful, means, something, spec...  
1      [take, easy, please, touch, gently, like, summ...  
2      [ill, never, know, go, put, lousy, rotten, sho...  
3      [making, somebody, happy, question, give, take...  
4      [making, somebody, happy, question, give, take...  
...                                                  ...  
57645  [irie, days, come, play, let, angels, fly, dev...  
57646  [power, workers, need, got, free, zone, workin...  
57647  [need, something, ill, believe, flashlights, h...  
57648  [northern, star, frightened, go, rest, cant, s...  
57649  [come, make, home, im, bit, late, hate, wait, ...  

[57650 rows x 5 columns]

In [13]:
df['Bag_of_words'] = ''
# # columns = ['artist','Key_words']

# # df["Bag_of_words"] = df['artist']+" "+ df["Key_words"].astype(str)
# # df["Bag_of_words"] = df[["artist", "Key_words"]].apply(" ".join, axis=1)
temp = " "
for i in range(len(df['text'])):
    temp = ' '.join([str(elem) for elem in df["Key_words"][i]])
    df['Bag_of_words'][i] = df['artist'][i] + " " + temp



In [14]:
df

artist                   song  \
0              abba  Ahe's My Kind Of Girl   
1              abba       Andante, Andante   
2              abba         As Good As New   
3              abba                   Bang   
4              abba       Bang-A-Boomerang   
...             ...                    ...   
57645  ziggy marley          Good Old Days   
57646  ziggy marley          Hand To Mouth   
57647          zwan           Come With Me   
57648          zwan                 Desire   
57649          zwan              Heartsong   

                                              link  \
0       /a/abba/ahes+my+kind+of+girl_20598417.html   
1            /a/abba/andante+andante_20002708.html   
2             /a/abba/as+good+as+new_20003033.html   
3                       /a/abba/bang_20598415.html   
4           /a/abba/bang+a+boomerang_20002668.html   
...                                            ...   
57645  /z/ziggy+marley/good+old+days_10198588.html   
57646  /z/ziggy+marley/hand+to+mouth_20531167.html   
57647           /z/zwan/come+with+me_20148981.html   
57648                 /z/zwan/desire_20148986.html   
57649              /z/zwan/heartsong_20148991.html   

                                                    text  \
0      Look at her face its a wonderful face  \r\nAnd...   
1      Take it easy with me please  \r\nTouch me gent...   
2      Ill never know why I had to go  \r\nWhy I had ...   
3      Making somebody happy is a question of give an...   
4      Making somebody happy is a question of give an...   
...                                                  ...   
57645  Irie days come on play  \r\nLet the angels fly...   
57646  Power to the workers  \r\nMore power  \r\nPowe...   
57647  all you need  \r\nis something ill believe  \r...   
57648  northern star  \r\nam i frightened  \r\nwhere ...   
57649  come in  \r\nmake yourself at home  \r\nim a b...   

                                               Key_words  \
0      [look, face, wonderful, means, something, spec...   
1      [take, easy, please, touch, gently, like, summ...   
2      [ill, never, know, go, put, lousy, rotten, sho...   
3      [making, somebody, happy, question, give, take...   
4      [making, somebody, happy, question, give, take...   
...                                                  ...   
57645  [irie, days, come, play, let, angels, fly, dev...   
57646  [power, workers, need, got, free, zone, workin...   
57647  [need, something, ill, believe, flashlights, h...   
57648  [northern, star, frightened, go, rest, cant, s...   
57649  [come, make, home, im, bit, late, hate, wait, ...   

                                            Bag_of_words  
0      abba look face wonderful means something speci...  
1      abba take easy please touch gently like summer...  
2      abba ill never know go put lousy rotten show b...  
3      abba making somebody happy question give take ...  
4      abba making somebody happy question give take ...  
...                                                  ...  
57645  ziggy marley irie days come play let angels fl...  
57646  ziggy marley power workers need got free zone ...  
57647  zwan need something ill believe flashlights ha...  
57648  zwan northern star frightened go rest cant sle...  
57649  zwan come make home im bit late hate wait hear...  

[57650 rows x 6 columns]

In [15]:
# df['Bag_of_words'] = df['Bag_of_words'].str.strip().str.replace(' ', ' ').str.replace('  ', ' ')

df_new = df[['song','Bag_of_words']]
df_new

song  \
0      Ahe's My Kind Of Girl   
1           Andante, Andante   
2             As Good As New   
3                       Bang   
4           Bang-A-Boomerang   
...                      ...   
57645          Good Old Days   
57646          Hand To Mouth   
57647           Come With Me   
57648                 Desire   
57649              Heartsong   

                                            Bag_of_words  
0      abba look face wonderful means something speci...  
1      abba take easy please touch gently like summer...  
2      abba ill never know go put lousy rotten show b...  
3      abba making somebody happy question give take ...  
4      abba making somebody happy question give take ...  
...                                                  ...  
57645  ziggy marley irie days come play let angels fl...  
57646  ziggy marley power workers need got free zone ...  
57647  zwan need something ill believe flashlights ha...  
57648  zwan northern star frightened go rest cant sle...  
57649  zwan come make home im bit late hate wait hear...  

[57650 rows x 2 columns]

In [16]:
df_1 = df_new.iloc[:int(len(df_new)/2),:]
df_2 = df_new.iloc[int(len(df_new)/2):,:]


In [17]:
df_1

song  \
0       Ahe's My Kind Of Girl   
1            Andante, Andante   
2              As Good As New   
3                        Bang   
4            Bang-A-Boomerang   
...                       ...   
28820  For Your Precious Love   
28821                Fraulein   
28822  Free Born Rambling Man   
28823     Fuzzy Was An Outlaw   
28824    Get A Little Dirt On   

                                            Bag_of_words  
0      abba look face wonderful means something speci...  
1      abba take easy please touch gently like summer...  
2      abba ill never know go put lousy rotten show b...  
3      abba making somebody happy question give take ...  
4      abba making somebody happy question give take ...  
...                                                  ...  
28820  david allan coe know first started album thoug...  
28821  david allan coe far across deep blue waters li...  
28822  david allan coe never meant leave intentions s...  
28823  david allan coe fuzzy outlaw swamp rat born ra...  
28824  david allan coe little boy daddy used say son ...  

[28825 rows x 2 columns]

In [18]:
count = CountVectorizer()
count_matrix = count.fit_transform(df_1['Bag_of_words'])
count_matrix
cosine_sim_1 = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim_1)

[[1.         0.06793662 0.13302601 ... 0.08633531 0.04003204 0.09857281]
 [0.06793662 1.         0.15105264 ... 0.06099943 0.01767767 0.1160762 ]
 [0.13302601 0.15105264 1.         ... 0.12797396 0.02966954 0.13393735]
 ...
 [0.08633531 0.06099943 0.12797396 ... 1.         0.10783277 0.1216975 ]
 [0.04003204 0.01767767 0.02966954 ... 0.10783277 1.         0.08977311]
 [0.09857281 0.1160762  0.13393735 ... 0.1216975  0.08977311 1.        ]]


In [19]:
count = CountVectorizer()
count_matrix = count.fit_transform(df_2['Bag_of_words'])
count_matrix
cosine_sim_2 = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim_2)

[[1.         0.10650585 0.1281237  ... 0.06134623 0.04911438 0.05170109]
 [0.10650585 1.         0.07055563 ... 0.0743212  0.03966818 0.04175738]
 [0.1281237  0.07055563 1.         ... 0.05201829 0.         0.07306622]
 ...
 [0.06134623 0.0743212  0.05201829 ... 1.         0.09139378 0.11544868]
 [0.04911438 0.03966818 0.         ... 0.09139378 1.         0.17972366]
 [0.05170109 0.04175738 0.07306622 ... 0.11544868 0.17972366 1.        ]]


In [21]:
cosine_sim = np.concatenate((cosine_sim_1,cosine_sim_2))
cosine_sim

array([[1.        , 0.06793662, 0.13302601, ..., 0.08633531, 0.04003204,
        0.09857281],
       [0.06793662, 1.        , 0.15105264, ..., 0.06099943, 0.01767767,
        0.1160762 ],
       [0.13302601, 0.15105264, 1.        , ..., 0.12797396, 0.02966954,
        0.13393735],
       ...,
       [0.06134623, 0.0743212 , 0.05201829, ..., 1.        , 0.09139378,
        0.11544868],
       [0.04911438, 0.03966818, 0.        , ..., 0.09139378, 1.        ,
        0.17972366],
       [0.05170109, 0.04175738, 0.07306622, ..., 0.11544868, 0.17972366,
        1.        ]])

In [22]:
print(cosine_sim)

[[1.         0.06793662 0.13302601 ... 0.08633531 0.04003204 0.09857281]
 [0.06793662 1.         0.15105264 ... 0.06099943 0.01767767 0.1160762 ]
 [0.13302601 0.15105264 1.         ... 0.12797396 0.02966954 0.13393735]
 ...
 [0.06134623 0.0743212  0.05201829 ... 1.         0.09139378 0.11544868]
 [0.04911438 0.03966818 0.         ... 0.09139378 1.         0.17972366]
 [0.05170109 0.04175738 0.07306622 ... 0.11544868 0.17972366 1.        ]]


In [26]:
indices = pd.Series(df['song'])

In [35]:
def recommend(title, cosine_sim = cosine_sim):
    recommended_movies = []
    idx = indices[indices == title].index[0]   # to get the index of the movie title matching the input song
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)   # similarity scores in descending order
    top_5_indices = list(score_series.iloc[1:6].index)   # to get the indices of top 6 most similar songs
    # [1:6] to exclude 0 (index 0 is the input song itself)
    
    for i in top_5_indices:   # to append the titles of top 10 similar songs to the recommended_movies list
        recommended_movies.append(list(df_new['song'])[i])
        
    return recommended_movies

In [36]:
recommend('As Good As New')

['Make Me Happy',
 'I Will Always Love You',
 'Give It Up',
 'I Need Love',
 "What I'm Looking For"]